name: Push Docker Image to Private Registry
run-name: Copy ${{ inputs.source_repo }} to ${{ inputs.destination_repo }}
on:
  workflow_dispatch:
    inputs:
      source:
        description: '镜像源 (Registry)'     
        required: true
        default: 'docker.io'
      destination:
        description: '目标源 (Registry)'
        required: true
        default: 'registry.cn-hangzhou.aliyuncs.com'
      source_repo:
        description: '仓库及标签 (格式 repo:tag)'
        required: true
        default: ''
      destination_repo:
        description: '目标仓库及标签 (格式 repo:tag)'
        required: true
        default: ''

jobs:
  push-to-private-registry:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Print input parameters
        run: |
          echo "Source Registry: ${{ github.event.inputs.source }}"
          echo "Destination Registry: ${{ github.event.inputs.destination }}"
          echo "Source Repository: ${{ github.event.inputs.source_repo }}"
          echo "Destination Repository: ${{ github.event.inputs.destination_repo }}"
    
      - name: Pull Docker image
        run: |
          echo "Pulling image from ${{ github.event.inputs.source }}/${{ github.event.inputs.source_repo }}"
          docker pull ${{ github.event.inputs.source }}/${{ github.event.inputs.source_repo }}
        
      - name: Tag Docker image for private registry
        run: |
          echo "Tagging image as ${{ github.event.inputs.destination }}/${{ github.event.inputs.destination_repo }}"
          docker tag ${{ github.event.inputs.source }}/${{ github.event.inputs.source_repo }} ${{ github.event.inputs.destination }}/${{ github.event.inputs.destination_repo }}
        
      - name: Login to private registry
        uses: docker/login-action@v2
        with:
          registry: ${{ github.event.inputs.destination }}
          username: ${{ secrets.DESTINATION_USERNAME }}
          password: ${{ secrets.DESTINATION_PASSWORD }}
          
      - name: Push to private registry
        run: |
          echo "Pushing image to ${{ github.event.inputs.destination }}/${{ github.event.inputs.destination_repo }}"
          docker push ${{ github.event.inputs.destination }}/${{ github.event.inputs.destination_repo }}
          echo "Push completed successfully"
